//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Smev.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_SMEVTYPE                    129
#define IDR_MAINFRAME1                  129
#define IDR_TOOLBAR_CAMERA              131
#define IDR_TOOLBAR_VORONOI             133
#define IDD_DIALOG_RANDOMIZER           135
#define IDD_DIALOG_BAR2                 136
#define IDD_DIALOG_ALPHA_SHAPE_PARAM    138
#define IDB_BMTREE_FACE                 139
#define IDB_BMTREE_FACE_SELECTED        140
#define IDD_DIALOG_OPTIONS              140
#define IDB_BMTREE_VERTEX               141
#define IDB_BMTREE_VERTEX_SELECTED      142
#define IDB_BMTREE_TETRA                143
#define IDB_BMTREE_TETRA_SELECTED       144
#define IDB_BITMAP2                     150
#define IDB_BITMAP_RECOV3D              151
#define IDD_DIALOG_LOCATION             152
#define IDR_CONTEXTMENU_CONTROL         154
#define IDD_DIALOG_INTRODUCTION         155
#define IDD_DIALOG_RECON_PROGRESS       156
#define IDC_SCROLLBAR1                  1000
#define IDC_SCROLLBAR_XAXIS             1000
#define IDC_SCROLLBAR_RANDOMIZER        1000
#define IDC_SCROLLBAR2                  1001
#define IDC_SCROLLBAR_YAXIS             1001
#define IDC_SCROLLBAR3                  1002
#define IDC_SCROLLBAR_XTRANS            1002
#define IDC_SCROLLBAR4                  1003
#define IDC_SCROLLBAR_ZTRANS            1003
#define IDC_COMBO_CAMERA_LOCATION       1008
#define IDC_RADIOACTUAL                 1010
#define IDC_RADIOVISDEBUG               1011
#define IDC_TREE_GEOMETRICAL            1013
#define IDC_EDIT_RANDOMIZER             1015
#define IDC_BUTTON1                     1016
#define IDC_BUTTON_ALPHA_SHAPE          1016
#define IDC_CHECK1                      1017
#define IDC_CHECKDELAUNAY               1017
#define IDC_CHECK_INVERT                1017
#define IDC_CHECK7                      1018
#define IDC_CHECKVERTNORMAL             1018
#define IDC_CHECKVORODIAGRAM            1019
#define IDC_BUTTON_LOCATION             1020
#define IDC_CHECK2                      1021
#define IDC_CHECKVORONOIVERTICES        1021
#define IDC_CHECK3                      1022
#define IDC_CHECKCONVEXHULL             1022
#define IDC_CHECK4                      1023
#define IDC_CHECKVOROCELL               1023
#define IDC_CHECK5                      1024
#define IDC_CHECKVORONOIBALL            1024
#define IDC_CHECK6                      1025
#define IDC_CHECKMedialBall             1025
#define IDC_CHECK8                      1026
#define IDC_CHECKMEDIALAXIS             1027
#define IDC_CHECK10                     1028
#define IDC_CHECK11                     1029
#define IDC_BUTTON2                     1030
#define IDC_BUTTON3                     1031
#define IDC_BUTTON_HIERARCHY            1031
#define IDC_CHECKPOINTCLOUD             1032
#define IDC_SLIDER_ALPHA_SHAPE          1032
#define IDC_CHECKSLIVERS                1033
#define IDC_EDIT_ALPHA_VALUE            1033
#define IDC_RADIO1                      1034
#define IDC_BUTTON_LAST1                1034
#define IDC_CHECKORIENTATION            1035
#define IDC_RADIO2                      1035
#define IDC_TAB5                        1036
#define IDC_RADIO3                      1036
#define IDC_BUTTON_Last2                1036
#define IDC_CHECKCRUSTEDGES             1037
#define IDC_RADIO4                      1037
#define IDC_BUTTON4                     1038
#define IDC_EDIT_NORMAL_FACTOR          1038
#define IDC_RADIO_FAR                   1038
#define IDC_BUTTON_LAST3                1038
#define IDC_BUTTON5                     1039
#define IDC_EDIT_MAXRADIUS_FACTOR       1039
#define IDC_RADIO_INSIDE                1039
#define IDC_BUTTON6                     1040
#define IDC_EDIT_SUPER_FACTOR           1040
#define IDC_RADIO_FRONT                 1040
#define IDC_BUTTON_DUALITY              1040
#define IDC_RADIO_TOP                   1041
#define IDC_BUTTON_Last4                1041
#define IDC_BUTTON7                     1042
#define IDC_RADIO_SIDE                  1042
#define IDC_RADIO_NEAR                  1043
#define IDC_RADIO_FOLLOW_POLE           1044
#define IDC_BUTTON_ACTUAL               1044
#define IDC_PROGRESS1                   1048
#define ID_RECON_DELAUNAY               32771
#define ID_BUTTON_ZPLUS                 32772
#define ID_RECON_CONVEX_HULL            32772
#define IDN                             32772
#define ID_BUTTON_ZMINUS                32773
#define ID_RECON_VORONOI                32773
#define ID_RECON_MEDIAL_AXIS            32774
#define ID_VIEW_WIREFRAME               32775
#define ID_RECON_CRUST                  32775
#define ID_VIEW_SOLID                   32776
#define ID_RECON_3DSR                   32776
#define ID_VIEW_GUORAUD                 32777
#define ID_ANALYSIS_STATISTICS          32777
#define ID_VIEW_PHONG                   32778
#define ID_ANALYSIS_VERIFICATION        32778
#define ID_VIEW_TEXTURE                 32779
#define ID_ANALYSIS_LOGGING             32779
#define ID_VIEW_GOURAUD                 32780
#define ID_ANALYSISTOOLS_ENDLOGGING     32780
#define ID_VIEW_SMOOTSHADING            32780
#define ID_VIEW_FLAT                    32781
#define ID_VIEW_VEREXTONLY              32782
#define ID_ANALYSIS_SLIVERS             32782
#define ID_VIEW_VERTEXONLY              32783
#define ID_GEOM_TOOLS_FACE_ORIENT       32784
#define ID_VIEW_POINTCLOUD              32785
#define ID_TOOLS_RANDOMIZE              32787
#define ID_VIEW_SHADED                  32788
#define ID_ANALYSIS_LOG_START           32788
#define ID_VIEW_WIRESHADED              32789
#define ID_ANALYSIS_LOG_END             32789
#define ID_VIEW_GRID                    32790
#define ID_VIEW_FLATSOLID               32791
#define ID_ACQUISITION                  32792
#define ID_VIEW_WIRESHADING             32793
#define ID_VISUALIZATION                32794
#define ID_BUTTON_CAMERA_TLEFT          32794
#define ID_VISUALIZATION_DATASTRUCTURES 32795
#define ID_BUTTON_CAMERA_TRIGHT         32795
#define ID_VISUALIZATION_NORMALS        32796
#define ID_BUTTON_CAMERA_TBACK          32796
#define ID_VISUALIZATION_FACE_NORMALS   32797
#define ID_BUTTON_CAMERA_TFRONT         32797
#define ID_VISUALIZATION_TEXTURE        32798
#define ID_VISUALIZATION_FACE_ORIENTATION 32799
#define ID_BUTTON_CAMERA_ROTATE_Y_CCW   32799
#define ID_VIEW_ZOOMIN                  32800
#define ID_BUTTON_CAMERA_ROTATE_Y_CW    32800
#define ID_VIEW_ZOOM_OUT                32801
#define ID_BUTTON_CAMERA_ROTATE_X_CCW   32801
#define ID_BUTTON_CAMERA_ROTATE_X_CW    32802
#define ID_TOOLS_OPTIONS                32803
#define ID_BUTTON_VORONOI_VERTICES      32803
#define ID_TOOLS_ALIGNMENT              32804
#define ID_FILE_IMPORT_PT2              32805
#define ID_BUTTON_VORONOI_PREV_SAMPLE   32805
#define ID_FILE_EXPORT_OBJ              32806
#define ID_ANALYSIS_DISPMAP_CRUST       32807
#define ID_BUTTON_VORONOI_NEXT_SAMPLE   32807
#define ID_BUTTON_VORONOI_CELL          32808
#define ID_VIEW_CAMERA_TOOLBAR          32812
#define ID_VIEW_VORONOI_TOOLBAR         32813
#define ID_HELP_ABOUTRECOVERY3D         32814
#define ID_TOOLS_OPTION                 32815
#define ID_VISUALIZATION_VIS_SNOOPER    32816
#define ID_HELP_ABOUT_R3D               32817
#define ID_VISUALISATION_FACEORIENT     32818
#define ID_VISUALIZATION_VISDEBUG       32819
#define ID_FILE_IMPORT_PT2FILE          32820
#define ID_ANALYSIS_DISPLACE_MAP_CRUST  32821
#define ID_RECONSTRUCTION_EXTRUCTCRUST  32822
#define ID_VIEW_MAX_BOX                 32823
#define ID_VIEW_BOUNDING_BOX            32824
#define ID_TOOLS_NORMALIZE_POINTS       32825
#define ID_RECONSTRUCTION_3DSR          32826
#define ID_FILE_IMPORT_NATIVE           32827
#define ID_VIEW_3DPLANE                 32828
#define ID_VIEW_COORDINATE_SYSTEM       32829
#define ID_TOOLS_FLAGGED_TETRA          32830
#define ID_RECON_VERTEX_NORMALS         32831
#define ID_VIEW_SUPER_TETRA             32832
#define ID_CONTEXT_CTRL_ROTATE_XY       32833
#define ID_CONTEXT_CTRL_TRANSLATE_XY    32834
#define ID_CONTEXT_CTRL_ROTRANS_Z       32835
#define ID_CONTEXT_CTRL_PICK_VERTEX     32836
#define ID_CONTEXT_CTRL_PICK_TRIANGLE   32837
#define ID_CONTEXT_CTRL_PICK_TETRAHEDRON 32838
#define ID_VIEW_LIGHT_TOGGLE            32839
#define ID_TOOLS_FLIP_VNORMALS          32840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
